### ISSUE TITLE
Connect to Plancast for attendance, etc. for events

### ISSUE THREAD

**Issue by mwarkentin** [ashchristopher/django-toronto#30]
### Simple

Add a field with the plancast id to the event model - this would let us link to the plancast page for an event
### Intermediate

<del>Add link to plancast, as well as a "I'm attending" link</del> This would require us to ask a user to login.. changing my mind for now.
### Advanced

Display a list of attendees with the [Plancast API](http://plancast.com/api#plans-show)

**Comment by mwarkentin** [comment]
I've implemented the plancast link:

![Plancast](http://skitch.michaelwarkentin.com/Django_Toronto_Meetup-20120715-120553.png)

**Comment by ashchristopher** [comment]
I wonder if we should change 'Add to calendar' to something more generic? Thoughts?

**Comment by mwarkentin** [comment]
Yeah, I was trying to come up with something different, but haven't got anything. It's not **terrible**.

**Comment by mwarkentin** [comment]
Played around with showing attendies pictures - thought it cluttered up the interface quite a bit. Pulling in the data was very easy.

If we wanted to move forward with something like this, we might want to look at limiting the number, or having a link that shows attendees in a popup.

Voting to close this issue for now.

**Comment by ashchristopher** [comment]
I agree. We can open a new issue if needed.
