### ISSUE TITLE
Event map isn't aligned

### ISSUE THREAD

**Issue by mwarkentin** [ashchristopher/django-toronto#33]
Removing the left margin from `.popin` would fix this.. not sure if it's in use anywhere else though.

![Alignment issue](http://skitch.michaelwarkentin.com/Django_Toronto_Meetup-20120715-122153.png)

**Comment by ashchristopher** [comment]
I suspect that I put that margin on purpose... thinking looked better. I agree though - lets fix the margin. Is it affected on the presetations list pages too? I think they use the .popin class.

**Comment by mwarkentin** [comment]
I don't see it anywhere on the presentations list page.

**Comment by ashchristopher** [comment]
Doh. I meant the events list page.

**Comment by mwarkentin** [comment]
Yeah, it's used there as well - but looks fine without the left margin.

![Events list page](http://skitch.michaelwarkentin.com/Django_Toronto_Meetup-20120715-162015.png)
