### ISSUE TITLE
User profile page.

### ISSUE THREAD

**Issue by ashchristopher** [ashchristopher/django-toronto#8]
- list of all presentations
- profile information
  - full name
  - current company
  - bio
  - image?
  - link to homepage?
  - linkedin?
  - twitter?
  - etc...
- github link

**Comment by mwarkentin** [comment]
Could use [gravatar](https://en.gravatar.com/) or [avatars.io](http://avatars.io/) to manage the profile images.

![Example](http://avatars.io/auto/ashchristopher) - http://avatars.io/auto/ashchristopher

**Comment by mwarkentin** [comment]
+1 for homepage, linkedin, twitter, facebook links
